// Code generated by go generate; DO NOT EDIT.
package note

const (
	C_1      pitchValue = 0
	Csharp_1 pitchValue = 1
	D_1      pitchValue = 2
	Dsharp_1 pitchValue = 3
	E_1      pitchValue = 4
	F_1      pitchValue = 5
	Fsharp_1 pitchValue = 6
	G_1      pitchValue = 7
	Gsharp_1 pitchValue = 8
	A_1      pitchValue = 9
	Asharp_1 pitchValue = 10
	B_1      pitchValue = 11
	C0       pitchValue = 12
	Csharp0  pitchValue = 13
	D0       pitchValue = 14
	Dsharp0  pitchValue = 15
	E0       pitchValue = 16
	F0       pitchValue = 17
	Fsharp0  pitchValue = 18
	G0       pitchValue = 19
	Gsharp0  pitchValue = 20
	A0       pitchValue = 21
	Asharp0  pitchValue = 22
	B0       pitchValue = 23
	C1       pitchValue = 24
	Csharp1  pitchValue = 25
	D1       pitchValue = 26
	Dsharp1  pitchValue = 27
	E1       pitchValue = 28
	F1       pitchValue = 29
	Fsharp1  pitchValue = 30
	G1       pitchValue = 31
	Gsharp1  pitchValue = 32
	A1       pitchValue = 33
	Asharp1  pitchValue = 34
	B1       pitchValue = 35
	C2       pitchValue = 36
	Csharp2  pitchValue = 37
	D2       pitchValue = 38
	Dsharp2  pitchValue = 39
	E2       pitchValue = 40
	F2       pitchValue = 41
	Fsharp2  pitchValue = 42
	G2       pitchValue = 43
	Gsharp2  pitchValue = 44
	A2       pitchValue = 45
	Asharp2  pitchValue = 46
	B2       pitchValue = 47
	C3       pitchValue = 48
	Csharp3  pitchValue = 49
	D3       pitchValue = 50
	Dsharp3  pitchValue = 51
	E3       pitchValue = 52
	F3       pitchValue = 53
	Fsharp3  pitchValue = 54
	G3       pitchValue = 55
	Gsharp3  pitchValue = 56
	A3       pitchValue = 57
	Asharp3  pitchValue = 58
	B3       pitchValue = 59
	C4       pitchValue = 60
	Csharp4  pitchValue = 61
	D4       pitchValue = 62
	Dsharp4  pitchValue = 63
	E4       pitchValue = 64
	F4       pitchValue = 65
	Fsharp4  pitchValue = 66
	G4       pitchValue = 67
	Gsharp4  pitchValue = 68
	A4       pitchValue = 69
	Asharp4  pitchValue = 70
	B4       pitchValue = 71
	C5       pitchValue = 72
	Csharp5  pitchValue = 73
	D5       pitchValue = 74
	Dsharp5  pitchValue = 75
	E5       pitchValue = 76
	F5       pitchValue = 77
	Fsharp5  pitchValue = 78
	G5       pitchValue = 79
	Gsharp5  pitchValue = 80
	A5       pitchValue = 81
	Asharp5  pitchValue = 82
	B5       pitchValue = 83
	C6       pitchValue = 84
	Csharp6  pitchValue = 85
	D6       pitchValue = 86
	Dsharp6  pitchValue = 87
	E6       pitchValue = 88
	F6       pitchValue = 89
	Fsharp6  pitchValue = 90
	G6       pitchValue = 91
	Gsharp6  pitchValue = 92
	A6       pitchValue = 93
	Asharp6  pitchValue = 94
	B6       pitchValue = 95
	C7       pitchValue = 96
	Csharp7  pitchValue = 97
	D7       pitchValue = 98
	Dsharp7  pitchValue = 99
	E7       pitchValue = 100
	F7       pitchValue = 101
	Fsharp7  pitchValue = 102
	G7       pitchValue = 103
	Gsharp7  pitchValue = 104
	A7       pitchValue = 105
	Asharp7  pitchValue = 106
	B7       pitchValue = 107
	C8       pitchValue = 108
	Csharp8  pitchValue = 109
	D8       pitchValue = 110
	Dsharp8  pitchValue = 111
	E8       pitchValue = 112
	F8       pitchValue = 113
	Fsharp8  pitchValue = 114
	G8       pitchValue = 115
	Gsharp8  pitchValue = 116
	A8       pitchValue = 117
	Asharp8  pitchValue = 118
	B8       pitchValue = 119
	C9       pitchValue = 120
	Csharp9  pitchValue = 121
	D9       pitchValue = 122
	Dsharp9  pitchValue = 123
	E9       pitchValue = 124
	F9       pitchValue = 125
	Fsharp9  pitchValue = 126
	G9       pitchValue = 127
)

var pitchValues = map[pitchValue]struct {
	name      string
	frequency float64
}{
	C_1:      {"C-1", 8.175798915643707},
	Csharp_1: {"C#-1", 8.661957218027252},
	D_1:      {"D-1", 9.177023997418988},
	Dsharp_1: {"D#-1", 9.722718241315029},
	E_1:      {"E-1", 10.300861153527183},
	F_1:      {"F-1", 10.913382232281373},
	Fsharp_1: {"F#-1", 11.562325709738577},
	G_1:      {"G-1", 12.249857374429663},
	Gsharp_1: {"G#-1", 12.978271799373287},
	A_1:      {"A-1", 13.75},
	Asharp_1: {"A#-1", 14.567617547440307},
	B_1:      {"B-1", 15.433853164253883},
	C0:       {"C0", 16.351597831287414},
	Csharp0:  {"C#0", 17.323914436054505},
	D0:       {"D0", 18.354047994837977},
	Dsharp0:  {"D#0", 19.445436482630058},
	E0:       {"E0", 20.601722307054366},
	F0:       {"F0", 21.826764464562746},
	Fsharp0:  {"F#0", 23.124651419477154},
	G0:       {"G0", 24.499714748859326},
	Gsharp0:  {"G#0", 25.956543598746574},
	A0:       {"A0", 27.5},
	Asharp0:  {"A#0", 29.13523509488062},
	B0:       {"B0", 30.86770632850775},
	C1:       {"C1", 32.70319566257483},
	Csharp1:  {"C#1", 34.64782887210901},
	D1:       {"D1", 36.70809598967594},
	Dsharp1:  {"D#1", 38.890872965260115},
	E1:       {"E1", 41.20344461410875},
	F1:       {"F1", 43.653528929125486},
	Fsharp1:  {"F#1", 46.24930283895431},
	G1:       {"G1", 48.99942949771867},
	Gsharp1:  {"G#1", 51.91308719749314},
	A1:       {"A1", 55},
	Asharp1:  {"A#1", 58.27047018976124},
	B1:       {"B1", 61.7354126570155},
	C2:       {"C2", 65.40639132514966},
	Csharp2:  {"C#2", 69.29565774421802},
	D2:       {"D2", 73.41619197935188},
	Dsharp2:  {"D#2", 77.78174593052023},
	E2:       {"E2", 82.4068892282175},
	F2:       {"F2", 87.30705785825097},
	Fsharp2:  {"F#2", 92.49860567790861},
	G2:       {"G2", 97.99885899543735},
	Gsharp2:  {"G#2", 103.82617439498628},
	A2:       {"A2", 110},
	Asharp2:  {"A#2", 116.54094037952248},
	B2:       {"B2", 123.47082531403103},
	C3:       {"C3", 130.8127826502993},
	Csharp3:  {"C#3", 138.59131548843604},
	D3:       {"D3", 146.83238395870382},
	Dsharp3:  {"D#3", 155.56349186104046},
	E3:       {"E3", 164.81377845643496},
	F3:       {"F3", 174.61411571650197},
	Fsharp3:  {"F#3", 184.99721135581723},
	G3:       {"G3", 195.99771799087463},
	Gsharp3:  {"G#3", 207.65234878997256},
	A3:       {"A3", 220},
	Asharp3:  {"A#3", 233.08188075904496},
	B3:       {"B3", 246.941650628062},
	C4:       {"C4", 261.6255653005986},
	Csharp4:  {"C#4", 277.1826309768721},
	D4:       {"D4", 293.6647679174076},
	Dsharp4:  {"D#4", 311.12698372208087},
	E4:       {"E4", 329.6275569128699},
	F4:       {"F4", 349.22823143300394},
	Fsharp4:  {"F#4", 369.99442271163446},
	G4:       {"G4", 391.99543598174927},
	Gsharp4:  {"G#4", 415.3046975799451},
	A4:       {"A4", 440},
	Asharp4:  {"A#4", 466.1637615180899},
	B4:       {"B4", 493.8833012561241},
	C5:       {"C5", 523.2511306011972},
	Csharp5:  {"C#5", 554.3652619537442},
	D5:       {"D5", 587.3295358348151},
	Dsharp5:  {"D#5", 622.2539674441618},
	E5:       {"E5", 659.2551138257398},
	F5:       {"F5", 698.4564628660078},
	Fsharp5:  {"F#5", 739.9888454232688},
	G5:       {"G5", 783.9908719634986},
	Gsharp5:  {"G#5", 830.6093951598903},
	A5:       {"A5", 880},
	Asharp5:  {"A#5", 932.3275230361799},
	B5:       {"B5", 987.7666025122483},
	C6:       {"C6", 1046.5022612023945},
	Csharp6:  {"C#6", 1108.7305239074883},
	D6:       {"D6", 1174.6590716696303},
	Dsharp6:  {"D#6", 1244.5079348883235},
	E6:       {"E6", 1318.5102276514795},
	F6:       {"F6", 1396.9129257320155},
	Fsharp6:  {"F#6", 1479.9776908465376},
	G6:       {"G6", 1567.981743926997},
	Gsharp6:  {"G#6", 1661.2187903197805},
	A6:       {"A6", 1760},
	Asharp6:  {"A#6", 1864.6550460723597},
	B6:       {"B6", 1975.533205024496},
	C7:       {"C7", 2093.004522404789},
	Csharp7:  {"C#7", 2217.4610478149766},
	D7:       {"D7", 2349.31814333926},
	Dsharp7:  {"D#7", 2489.015869776647},
	E7:       {"E7", 2637.02045530296},
	F7:       {"F7", 2793.825851464031},
	Fsharp7:  {"F#7", 2959.955381693075},
	G7:       {"G7", 3135.9634878539946},
	Gsharp7:  {"G#7", 3322.437580639561},
	A7:       {"A7", 3520},
	Asharp7:  {"A#7", 3729.3100921447194},
	B7:       {"B7", 3951.066410048992},
	C8:       {"C8", 4186.009044809578},
	Csharp8:  {"C#8", 4434.922095629953},
	D8:       {"D8", 4698.63628667852},
	Dsharp8:  {"D#8", 4978.031739553294},
	E8:       {"E8", 5274.04091060592},
	F8:       {"F8", 5587.651702928062},
	Fsharp8:  {"F#8", 5919.91076338615},
	G8:       {"G8", 6271.926975707989},
	Gsharp8:  {"G#8", 6644.875161279122},
	A8:       {"A8", 7040},
	Asharp8:  {"A#8", 7458.620184289437},
	B8:       {"B8", 7902.132820097988},
	C9:       {"C9", 8372.018089619156},
	Csharp9:  {"C#9", 8869.844191259906},
	D9:       {"D9", 9397.272573357044},
	Dsharp9:  {"D#9", 9956.063479106588},
	E9:       {"E9", 10548.081821211836},
	F9:       {"F9", 11175.303405856126},
	Fsharp9:  {"F#9", 11839.8215267723},
	G9:       {"G9", 12543.853951415975},
}
